Team-Packman/Packman-Server-Spring

- src/main/java/packman/controller/UserController.java
- src/main/java/packman/dto/user/UserInfoResponseDto.java
- src/main/java/packman/service/UserService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-21](https://packman-team.atlassian.net/browse/PS-21?atlOrigin=eyJpIjoiMDI2YmU4NGQyZWI1NDA2MmI5M2ViZTRiMjNkOWVhNjAiLCJwIjoiaiJ9)
- 유저 조회 API 구현
- 
[PS-21]: https://packman-team.atlassian.net/browse/PS-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 유저 조회 API

- src/main/java/packman/controller/UserController.java
- src/main/java/packman/entity/User.java
- src/main/java/packman/repository/UserRepository.java
- src/main/java/packman/service/UserService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-22](https://packman-team.atlassian.net/browse/PS-22?atlOrigin=eyJpIjoiNTRhMTI5NTc5ZTQ5NGZmMTlmZTVkMjMyODZjYWUwZTgiLCJwIjoiaiJ9)
-  유저 탈퇴 API 구현
- 
[PS-22]: https://packman-team.atlassian.net/browse/PS-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 유저 탈퇴 API

- src/main/java/packman/controller/FolderController.java
- src/main/java/packman/dto/folder/FolderAloneListMapping.java
- src/main/java/packman/dto/folder/TogetherListsInFolderResponseDto.java
- src/main/java/packman/dto/list/ListIdMapping.java
- src/main/java/packman/dto/list/TogetherAloneListMapping.java
- src/main/java/packman/repository/FolderPackingListRepository.java
- src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
- src/main/java/packman/service/FolderService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-30](https://packman-team.atlassian.net/browse/PS-30?atlOrigin=eyJpIjoiMjVlZWRkNDJhZDc3NDhhYTk4Zjg0OTA1NDkxYzkwNWMiLCJwIjoiaiJ9)
- 폴더 속 함께 패킹리스트 조회 API 구현
- 
[PS-30]: https://packman-team.atlassian.net/browse/PS-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 폴더 속 함께 패킹리스트 조회 

- build.gradle
- src/main/java/packman/controller/ListController.java
- src/main/java/packman/dto/list/ListTitleRequestDto.java
- src/main/java/packman/dto/list/ListTitleResponseDto.java
- src/main/java/packman/repository/FolderPackingListRepository.java
- src/main/java/packman/repository/UserRepository.java
- src/main/java/packman/repository/packingList/PackingListRepository.java
- src/main/java/packman/service/ListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/LengthValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-34](https://packman-team.atlassian.net/browse/PS-34?atlOrigin=eyJpIjoiYzYxYjY3MWNlZTk3NGI2N2FiZTI4YWU5MmQzMDcxOTIiLCJwIjoiaiJ9)
- 패킹리스트 제목 수정
- 
[PS-34]: https://packman-team.atlassian.net/browse/PS-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 패킹리스트 제목 수정

- src/main/java/packman/controller/ListController.java
- src/main/java/packman/dto/list/DepartureDateRequestDto.java
- src/main/java/packman/dto/list/DepartureDateResponseDto.java
- src/main/java/packman/entity/packingList/PackingList.java
- src/main/java/packman/service/ListService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-35](https://packman-team.atlassian.net/browse/PS-35?atlOrigin=eyJpIjoiMDAzMGY2YTVmZTJiNGFkYWFkNGY3NjEyM2JkNDBiNzQiLCJwIjoiaiJ9)
- 패킹리스트 출발 날짜 수정
- 
[PS-35]: https://packman-team.atlassian.net/browse/PS-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 패킹리스트 출발 날짜 수정

- src/main/java/packman/controller/aloneList/AloneListPackController.java
- src/main/java/packman/dto/category/CategoryResponseDto.java
- src/main/java/packman/dto/list/ListResponseMapping.java
- src/main/java/packman/dto/pack/PackCreateDto.java
- src/main/java/packman/entity/Category.java
- src/main/java/packman/entity/Pack.java
- src/main/java/packman/repository/packingList/PackingListRepository.java
- src/main/java/packman/service/aloneList/AloneListCategoryService.java
- src/main/java/packman/service/aloneList/AloneListPackService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/LengthValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-48](https://packman-team.atlassian.net/browse/PS-48?atlOrigin=eyJpIjoiNDg4Mzg1MzBhMmFjNGZhNjljNmNlNmQ2ZDJlZThlMDMiLCJwIjoiaiJ9)
- 혼자 패킹리스트 짐 생성
- 겹치는 validate가 많아서 따로 폴더 만들어서 분리했습니다~ 확인 해주세용~😊
[PS-48]: https://packman-team.atlassian.net/browse/PS-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 혼자 패킹리스트 짐 생성 API

- src/main/java/packman/controller/aloneList/AloneListPackController.java
- src/main/java/packman/service/aloneList/AloneListPackService.java
- src/main/java/packman/util/ExceptionHandler.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-50](https://packman-team.atlassian.net/browse/PS-50?atlOrigin=eyJpIjoiZWYxYmYyZjg5YjE4NGNmNGIxNzk5NTUzZDBlZGI5ZDciLCJwIjoiaiJ9)
- 혼자 패킹리스트 짐 삭제 API
- 
[PS-50]: https://packman-team.atlassian.net/browse/PS-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 혼자 패킹리스트 짐 삭제 API

- src/main/java/packman/controller/togetherList/TogetherListController.java
- src/main/java/packman/dto/togetherList/TogetherListInviteResponseDto.java
- src/main/java/packman/entity/packingList/PackingList.java
- src/main/java/packman/repository/UserGroupRepository.java
- src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
- src/main/java/packman/repository/packingList/TogetherPackingListRepository.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-16](https://packman-team.atlassian.net/browse/PS-16)
- 
- 
[PS-16]: https://packman-team.atlassian.net/browse/PS-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 함께 패킹 초대

- src/main/java/packman/controller/aloneList/AloneListCategoryController.java
- src/main/java/packman/controller/togetherList/TogetherListCategoryController.java
- src/main/java/packman/dto/category/CategoryUpdateDto.java
- src/main/java/packman/entity/packingList/PackingList.java
- src/main/java/packman/service/aloneList/AloneListCategoryService.java
- src/main/java/packman/service/togetherList/TogetherListCategoryService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/DuplicatedValidator.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/LengthValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-40](https://packman-team.atlassian.net/browse/PS-40)
- 함께 패킹 카테고리 수정 api 구현
- 
[PS-40]: https://packman-team.atlassian.net/browse/PS-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 함께 패킹 카테고리 수정 api

- src/main/java/packman/controller/aloneList/AloneListCategoryController.java
- src/main/java/packman/controller/togetherList/TogetherListCategoryController.java
- src/main/java/packman/dto/category/CategoryUpdateDto.java
- src/main/java/packman/entity/Category.java
- src/main/java/packman/entity/packingList/PackingList.java
- src/main/java/packman/service/aloneList/AloneListCategoryService.java
- src/main/java/packman/service/togetherList/TogetherListCategoryService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/DuplicatedValidator.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/LengthValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-38](https://packman-team.atlassian.net/browse/PS-38)
- 혼자 패킹 리스트 카테고리 삭제 api
- 유저의 리스트인지 검사하는 validation 추가 (나머지 혼자 패킹리스트 카테고리 생성, 수정에도 적용 예정)
[PS-38]: https://packman-team.atlassian.net/browse/PS-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 혼자 패킹 리스트 카테고리 삭제 api

- src/main/java/packman/controller/togetherList/TogetherListController.java
- src/main/java/packman/dto/member/MemberAddDto.java
- src/main/java/packman/dto/member/MemberResponseDto.java
- src/main/java/packman/entity/Folder.java
- src/main/java/packman/entity/FolderPackingList.java
- src/main/java/packman/entity/Group.java
- src/main/java/packman/entity/UserGroup.java
- src/main/java/packman/entity/packingList/AlonePackingList.java
- src/main/java/packman/entity/packingList/PackingList.java
- src/main/java/packman/entity/packingList/TogetherAlonePackingList.java
- src/main/java/packman/entity/packingList/TogetherPackingList.java
- src/main/java/packman/repository/FolderRepository.java
- src/main/java/packman/service/FolderService.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/DuplicatedValidator.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-44]https://packman-team.atlassian.net/browse/PS-44)
- 멤버원으로 추가 API
- 유저의 기본 폴더에 리스트 추가
- 함께 속 혼자 패킹 생성
- 기본 카테고리 추가 
[PS-44]: https://packman-team.atlassian.net/browse/PS-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 멤버원 추가 API

- src/main/java/packman/controller/ListController.java
- src/main/java/packman/dto/list/ListResponseDto.java
- src/main/java/packman/repository/packingList/AlonePackingListRepository.java
- src/main/java/packman/service/ListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- [PS-58](https://packman-team.atlassian.net/browse/PS-58)
- 패킹리스트 날짜, 제목 조회 API
[PS-58]: https://packman-team.atlassian.net/browse/PS-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 패킹리스트 날짜, 제목 조회 API

- src/main/java/packman/controller/TemplateController.java
- src/main/java/packman/dto/folder/FolderUpdateRequestDto.java
- src/main/java/packman/dto/template/TemplateCategoryMapping.java
- src/main/java/packman/dto/template/TemplatePackInfo.java
- src/main/java/packman/dto/template/TemplateResponseDto.java
- src/main/java/packman/dto/template/TemplateResponseMapping.java
- src/main/java/packman/repository/template/TemplateRepository.java
- src/main/java/packman/service/TemplateService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/Validator.java
- [PS-43](https://packman-team.atlassian.net/browse/PS-43)
- 템플릿 상세조회
[PS-43]: https://packman-team.atlassian.net/browse/PS-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 템플릿 상세 조회 API

- src/main/java/packman/controller/aloneList/AloneListController.java
- src/main/java/packman/dto/list/DetailedAloneListResponseDto.java
- src/main/java/packman/repository/FolderPackingListRepository.java
- src/main/java/packman/repository/packingList/PackingListRepository.java
- src/main/java/packman/service/aloneList/AloneListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- [PS-24](https://packman-team.atlassian.net/browse/PS-24?atlOrigin=eyJpIjoiMWQ4YzMxNmQ1Y2I2NDY0YzlhNTUyZTA0YWQ5YjgxNTciLCJwIjoiaiJ9)
- 혼자 패킹리스트 상세조회 구현
- 
[PS-24]: https://packman-team.atlassian.net/browse/PS-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 혼자패킹리스트 상세 조회 API

- src/main/java/packman/controller/TemplateController.java
- src/main/java/packman/dto/template/AloneTemplateListResponseDto.java
- src/main/java/packman/dto/template/TemplateIdTitleMapping.java
- src/main/java/packman/dto/template/TemplateListResponseDto.java
- src/main/java/packman/repository/template/TemplateRepository.java
- src/main/java/packman/service/TemplateService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-59](https://packman-team.atlassian.net/browse/PS-59?atlOrigin=eyJpIjoiMzFlNjQyZGRlMTNlNDllNDhjYzY4MGZiOGQ1NzYzN2YiLCJwIjoiaiJ9)
- 혼자 패킹 템플릿 리스트 조회 구현
- 
[PS-59]: https://packman-team.atlassian.net/browse/PS-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 혼자 패킹 템플릿 리스트 조회 API

- src/main/java/packman/controller/TemplateController.java
- src/main/java/packman/service/TemplateService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-60](https://packman-team.atlassian.net/browse/PS-60?atlOrigin=eyJpIjoiMDgxMmI3YjI0MTM5NDE4YWJmMmQ4NDQwYTFmMGM4YjIiLCJwIjoiaiJ9)
- 함께 패킹 템플릿 리스트 조회 구현
- 
[PS-60]: https://packman-team.atlassian.net/browse/PS-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 함께 패킹 템플릿 리스트 조회 API

- src/main/java/packman/controller/togetherList/TogetherListController.java
- src/main/java/packman/dto/togetherList/PackerUpdateDto.java
- src/main/java/packman/repository/PackRepository.java
- src/main/java/packman/repository/UserGroupRepository.java
- src/main/java/packman/repository/packingList/PackingListRepository.java
- src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
- src/main/java/packman/repository/packingList/TogetherPackingListRepository.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-18](https://packman-team.atlassian.net/browse/PS-18?atlOrigin=eyJpIjoiNWY3NTY0ZWY4OTMyNDFiYWFmMjc2ZDMxZjdiOWIxNjYiLCJwIjoiaiJ9)
- 함께 패킹리스트 담당자 배정
- 
[PS-18]: https://packman-team.atlassian.net/browse/PS-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 함께 패킹리스트 담당자 배정

- src/main/java/packman/controller/togetherList/TogetherListController.java
- src/main/java/packman/dto/list/DetaildTogetherListResponseDto.java
- src/main/java/packman/repository/UserGroupRepository.java
- src/main/java/packman/repository/packingList/PackingListRepository.java
- src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-13](https://packman-team.atlassian.net/browse/PS-13?atlOrigin=eyJpIjoiOGI2NWQyZWU5ZjU4NDliYmE5MTU5ZmQyNDkwOWMwNTAiLCJwIjoiaiJ9)
- 함께 패킹리스트 상세 조회
- 
[PS-13]: https://packman-team.atlassian.net/browse/PS-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 함께 패킹리스트 상세 조회

- src/main/java/packman/controller/ListController.java
- src/main/java/packman/dto/list/TemplateUpdateDto.java
- src/main/java/packman/dto/list/UpdatedTemplateResponseDto.java
- src/main/java/packman/entity/packingList/PackingList.java
- src/main/java/packman/entity/template/Template.java
- src/main/java/packman/entity/template/TemplateCategory.java
- src/main/java/packman/entity/template/TemplatePack.java
- src/main/java/packman/repository/FolderPackingListRepository.java
- src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
- src/main/java/packman/repository/template/TemplateCategoryRepository.java
- src/main/java/packman/repository/template/TemplateRepository.java
- src/main/java/packman/service/ListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/IdValidator.java
- src/main/java/packman/validator/Validator.java
- [PS-61](https://packman-team.atlassian.net/browse/PS-61?atlOrigin=eyJpIjoiNjA2NThkNDIwNzQ0NGJmMWE5M2QyMTEwZGUyOWRjNjQiLCJwIjoiaiJ9)
- 패킹리스트 나만의 템플릿 추가 및 업데이트
- 
[PS-61]: https://packman-team.atlassian.net/browse/PS-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 패킹리스트 나만의 템플릿 추가 및 업데이트

- src/main/java/packman/controller/FolderController.java
- src/main/java/packman/controller/ListController.java
- src/main/java/packman/dto/list/RecentCreatedListResponseDto.java
- src/main/java/packman/repository/packingList/AlonePackingListRepository.java
- src/main/java/packman/service/FolderService.java
- src/main/java/packman/util/ResponseCode.java
- [PS-28](https://packman-team.atlassian.net/browse/PS-28?atlOrigin=eyJpIjoiOGYwYTI3ZjZlZWUxNDZmODlhNGQ2YmU2N2M3ODdmN2EiLCJwIjoiaiJ9)
- 최근 생성된 리스트 조회 API
- 
[PS-28]: https://packman-team.atlassian.net/browse/PS-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 최근 생성된 리스트 조회 API

- src/main/java/packman/controller/aloneList/AloneListPackController.java
- src/main/java/packman/controller/togetherList/TogetherListPackController.java
- src/main/java/packman/service/PackService.java
- src/main/java/packman/service/aloneList/AloneListCategoryService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/Validator.java
- [PS-53](https://packman-team.atlassian.net/browse/PS-53?atlOrigin=eyJpIjoiMzgyMGExNDQ5MWM0NDk4OWFjOTc2OWJjMWZjYzJhZTkiLCJwIjoiaiJ9)
- 함께 패킹리스트 짐 삭제 API
- 혼자 패킹리스트 관련 validate 메서드 통합
- 패킹리스트, 카테고리, 짐 관계를 검사하는 메서드 분리
[PS-53]: https://packman-team.atlassian.net/browse/PS-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 함께 패킹리스트 짐 삭제 API

- src/main/java/packman/controller/aloneList/AloneListController.java
- src/main/java/packman/dto/list/InviteAloneListResponseDto.java
- src/main/java/packman/repository/packingList/AlonePackingListRepository.java
- src/main/java/packman/service/aloneList/AloneListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/Validator.java
- [PS-55](https://packman-team.atlassian.net/browse/PS-55?atlOrigin=eyJpIjoiYzM1Yzg0ZmU1NGQwNDgwNjkwZTg0NTg3ZWYxMWI0ZWYiLCJwIjoiaiJ9)
- 혼자 패킹리스트 초대 API 구현
- 
[PS-55]: https://packman-team.atlassian.net/browse/PS-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 혼자 패킹리스트 초대 API

- src/main/java/packman/controller/ListController.java
- src/main/java/packman/dto/list/InviteListResponseDto.java
- src/main/java/packman/dto/user/PackerInfo.java
- src/main/java/packman/service/ListService.java
- src/main/java/packman/util/ResponseCode.java
- src/main/java/packman/validator/Validator.java
- [PS-54](https://packman-team.atlassian.net/browse/PS-54?atlOrigin=eyJpIjoiNzJjZjBkMzY0YTE5NGYwOTgwODZlNDBhYTkyNTcxNGMiLCJwIjoiaiJ9)
- 공유된 패킹리스트 조회 API 구현
- listType에 따른 리스트 조회
[PS-54]: https://packman-team.atlassian.net/browse/PS-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 공유된 패킹리스트 조회 API

- src/main/java/packman/dto/list/DetaildTogetherListResponseDto.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- [PS-63](https://packman-team.atlassian.net/browse/PS-63?atlOrigin=eyJpIjoiNWY0ZDFjMzcwYzI3NDE0N2E3M2Y5ZTIzYWY3NjMwYzUiLCJwIjoiaiJ9)
- 함께 패킹리스트 상세 조회 response body에서 isMember 삭제
- 
[PS-63]: https://packman-team.atlassian.net/browse/PS-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: 함께 패킹리스트 상세 조회 response body에서 isMember 삭제

- src/main/java/packman/auth/CorsFilter.java
- src/main/java/packman/auth/SecurityConfig.java
> feat: corsFilter 설정

- src/main/java/packman/auth/filter/CorsFilter.java
> fix: corsFilter 설정

- src/main/java/packman/auth/filter/CorsFilter.java
> feat: cors 허용 url 추가

- src/main/java/packman/auth/filter/CorsFilter.java
> chore: cors 허용 url 수정

- src/main/java/packman/auth/filter/CorsFilter.java
> fix: 여러 url을 originHeader에 등록

- src/main/java/packman/auth/filter/CorsFilter.java
> fix: localhost:3000만 허용하도록 수정

- src/main/java/packman/auth/filter/CorsFilter.java
> feat: 임시적으로 모든 url 접근 가능하도록 허용

- scripts/stop.sh
- 실행중인 애플리케이션의 pid를 deploy.log에 기록
-
> ci: 실행중인 애플리케이션의 pid를 deploy.log에 기록

- scripts/start.sh
- scripts/stop.sh
- 실행 중인 pid를 확인하는 경로 변경
- 기존 경로는 실행 중인 pid를 찾지 못해서 `packman.jar`로 찾도록 수정
> ci: 실행 중인 pid를 확인하는 경로 변경

- scripts/start.sh
> ci: nohup배포 전 경로 이동 추가

- src/main/java/packman/service/AuthService.java
- [PS-68](https://packman-team.atlassian.net/browse/PS-68?atlOrigin=eyJpIjoiMTM0NTg2N2U0ODNlNDZkOGEzMWVkMGZmYTlkNTA3ZjYiLCJwIjoiaiJ9)
- 카카오 로그인 선택항목 동의 안했을 때 빈 문자열 처리
- 
[PS-68]: https://packman-team.atlassian.net/browse/PS-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 카카오 로그인 선택항목 동의 안했을 때 빈 문자열 처리

- src/main/java/packman/controller/MemberController.java
- src/main/java/packman/service/MemberService.java
- src/main/java/packman/validator/IdValidator.java
- [PS-69](https://packman-team.atlassian.net/browse/PS-69?atlOrigin=eyJpIjoiMTE0ZDdhMDIzNmRmNDU2OThiZTlkMzQ4ZTRmZDRkZmQiLCJwIjoiaiJ9)
- 함께 패킹 멤버 삭제 path parameter groupId를 통합 listId로 수정
- 
[PS-69]: https://packman-team.atlassian.net/browse/PS-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 함께 패킹 멤버 삭제 path parameter groupId를 통합 listId로 수정

- src/main/java/packman/dto/togetherList/TogetherListInviteResponseDto.java
- src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- src/main/java/packman/validator/Validator.java
- [PS-71](https://packman-team.atlassian.net/browse/PS-71)
- 
- 
[PS-71]: https://packman-team.atlassian.net/browse/PS-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 함께 패킹 초대 응답 id 수정

- src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
- src/main/java/packman/validator/Validator.java
- [PS-71](https://packman-team.atlassian.net/browse/PS-71)
- find0ne-> findTop1으로 jpa 변경
- 
[PS-71]: https://packman-team.atlassian.net/browse/PS-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: findOne -> findTop1

- src/main/java/packman/service/aloneList/AloneListCategoryService.java
- src/main/java/packman/service/togetherList/TogetherListCategoryService.java
- [PS-72](https://packman-team.atlassian.net/browse/PS-72)
- 카테고리 삭제할 때 id비교를 !=에서 equals로 변경했습니다(분명히 테스트 했던 것 같은데 암소소리^&^)
- 
[PS-72]: https://packman-team.atlassian.net/browse/PS-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 카테고리 삭제 에러 수정

- src/main/java/packman/controller/aloneList/AloneListController.java
- src/main/java/packman/service/aloneList/AloneListService.java
- [PS-74](https://packman-team.atlassian.net/browse/PS-74?atlOrigin=eyJpIjoiZDU4YTJiYmI5NTg1NDBiMGJhMmIwNzZjNzIyZjE1MjEiLCJwIjoiaiJ9)
- 혼자 패킹리스트 조회 초대코드 query parameter 추가
- 본인 패킹리스트 조회 / 초대코드로 패킹리스트 조회 구현
- 
[PS-74]: https://packman-team.atlassian.net/browse/PS-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 혼자 패킹리스트 조회 초대코드 query parameter 추가

- src/main/java/packman/entity/packingList/AlonePackingList.java
- src/main/java/packman/entity/packingList/TogetherAlonePackingList.java
- src/main/java/packman/repository/packingList/AlonePackingListRepository.java
- src/main/java/packman/service/ListService.java
- [PS-73](https://packman-team.atlassian.net/browse/PS-73)
- qa에서 함께 패킹리스트 제목, 날짜 수정이 적용안되는 에러 발생
- 기존에는 수정하면 함께 패킹리스트만 수정되었지만 함께 패킹 멤버의 모든 혼자 패킹도 수정 적용
[PS-73]: https://packman-team.atlassian.net/browse/PS-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 함께 패킹리스트 제목 날짜 수정시 혼자 패킹도 수정되도록

- src/main/java/packman/controller/ListController.java
- src/main/java/packman/service/ListService.java
- [PS-76](https://packman-team.atlassian.net/browse/PS-76)
-  패킹리스트 제목, 날짜 조회에서 invite 쿼리 파라미터 추가
- 현지가 코리 안해줌,,,,
[PS-76]: https://packman-team.atlassian.net/browse/PS-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 패킹리스트 제목 & 날짜 query parameter 추가

- .github/workflows/develop-deploy.yml
- .github/workflows/main-deploy.yml
- src/main/java/packman/service/ListService.java
- develop branch배포, main branch 배포 설정
> ci: develop branch배포, main branch 배포 설정

- src/main/java/packman/controller/AuthController.java
- [PS-79](https://packman-team.atlassian.net/browse/PS-79?atlOrigin=eyJpIjoiODVjOGZhZjUxMDBkNGEyN2EzYWE2MThhZDg3YmEyYzYiLCJwIjoiaiJ9)
- 토큰 재발급 api cors 설정
- 
[PS-79]: https://packman-team.atlassian.net/browse/PS-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 토큰 재발급 api cors 설정

- src/main/java/packman/dto/list/DetaildTogetherListResponseDto.java
- src/main/java/packman/dto/list/TogetherListDto.java
- src/main/java/packman/dto/list/TogetherListResponseDto.java
- src/main/java/packman/dto/list/alone/MyListDto.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- [PS-80](https://packman-team.atlassian.net/browse/PS-80?atlOrigin=eyJpIjoiNGQyNzFmZGRiZGVmNDE4MGFhNGYyNjY4OGQ1OWIwYWYiLCJwIjoiaiJ9)
- 함께 패킹리스트 생성 responseBody의 isSaved 수정
- 함께 패킹리스트 조회 responseBody의 isSaved 수정
- 
[PS-80]: https://packman-team.atlassian.net/browse/PS-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: 함께 패킹리스트 생성/조회 responseBody의 isSaved 수정

- src/main/java/packman/auth/JwtTokenProvider.java
- [PS-81](https://packman-team.atlassian.net/browse/PS-81?atlOrigin=eyJpIjoiZjFhZGM4ODFmOGVkNDgwMGIyMmQ1ZDVmNzFlOTRhODUiLCJwIjoiaiJ9)
- 만료된 토큰 이외의 jwt exception을 invalid_token으로 처리
- 
[PS-81]: https://packman-team.atlassian.net/browse/PS-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: 만료된 토큰 이외의 jwt exception을 invalid_token으로 처리

- src/main/java/packman/dto/list/alone/MyListDto.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- [PS-82](https://packman-team.atlassian.net/browse/PS-82?atlOrigin=eyJpIjoiMmFlZjVkMTg2YzhhNDEyZWEwYzI2OWFkNzUzMjc4NDQiLCJwIjoiaiJ9)
- 함께 패킹리스트 생성, 조회 responseBody 수정
- 
[PS-82]: https://packman-team.atlassian.net/browse/PS-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 함께 패킹리스트 생성, 조회 responseBody 수정

- .gitignore
- src/main/java/packman/auth/JwtAuthenticationFilter.java
- src/main/java/packman/auth/filter/LogbackFilter.java
- src/main/java/packman/dto/list/DepartureDateResponseDto.java
- src/main/java/packman/dto/list/ListTitleResponseDto.java
- src/main/java/packman/dto/log/AloneListLogDto.java
- src/main/java/packman/dto/log/TogetherListLogDto.java
- src/main/java/packman/dto/log/UserLogDto.java
- src/main/java/packman/dto/member/MemberAddResponseDto.java
- src/main/java/packman/dto/togetherList/TogetherListInviteResponseDto.java
- src/main/java/packman/service/AlarmService.java
- src/main/java/packman/service/HelpService.java
- src/main/java/packman/service/ListService.java
- src/main/java/packman/service/PackService.java
- src/main/java/packman/service/TemplateService.java
- src/main/java/packman/service/UserService.java
- src/main/java/packman/service/aloneList/AloneListCategoryService.java
- src/main/java/packman/service/aloneList/AloneListService.java
- src/main/java/packman/service/togetherList/TogetherListCategoryService.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- src/main/java/packman/util/ExceptionHandler.java
- src/main/java/packman/util/LogMessage.java
- src/main/resources/console-appender.xml
- src/main/resources/file-error-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/file-warn-appender.xml
- src/main/resources/logback-spring.xml
- [PS-75](https://packman-team.atlassian.net/browse/PS-75?atlOrigin=eyJpIjoiY2U3MGQ3NTMyYzAzNDQxNWI3ZDQyODMyNjE1OGViMzEiLCJwIjoiaiJ9)
- 사용자 분석용 로그 설정
- exception 로그 설정
- 
[PS-75]: https://packman-team.atlassian.net/browse/PS-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 로그 파일 설정

- src/main/java/packman/controller/AuthController.java
- [PS-85](https://packman-team.atlassian.net/browse/PS-85)
- cors origin 변경
[PS-85]: https://packman-team.atlassian.net/browse/PS-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: cors origin 변경

- src/main/java/packman/controller/AuthController.java
- src/main/java/packman/dto/user/UserCreateDto.java
- [PS-85](https://packman-team.atlassian.net/browse/PS-85)
[PS-85]: https://packman-team.atlassian.net/browse/PS-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: cors local, dev, prod 추가 및 builder 오류

- src/main/java/packman/auth/JwtAuthenticationFilter.java
- src/main/java/packman/auth/JwtTokenProvider.java
- src/main/java/packman/auth/SecurityConfig.java
- src/main/java/packman/auth/filter/CorsFilter.java
- src/main/java/packman/controller/AuthController.java
- src/main/java/packman/service/AuthService.java
- src/main/java/packman/validator/Validator.java
- [PS-83](https://packman-team.atlassian.net/browse/PS-83?atlOrigin=eyJpIjoiZWNiZmViMTQ1YzY5NDg4ZmJjODM5Y2QwNTg3MWUxOTUiLCJwIjoiaiJ9)
- 토큰 재발급 api cors 해결
- cors 허용 url local, dev, prod 3개 등록
- 
[PS-83]: https://packman-team.atlassian.net/browse/PS-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 토큰 재발급 api cors 해결

- src/main/java/packman/auth/JwtAuthenticationFilter.java
- src/main/java/packman/entity/template/Template.java
- src/main/java/packman/repository/template/TemplateRepository.java
- src/main/java/packman/service/TemplateService.java
- [PS-86](https://packman-team.atlassian.net/browse/PS-86?atlOrigin=eyJpIjoiMjdkMjMxMzcwMzAyNDMzMzliNWI5YmU2OWYzMGU0ZmQiLCJwIjoiaiJ9)
- 템플릿 created_at, updated_at 추가 및 수정
- 
[PS-86]: https://packman-team.atlassian.net/browse/PS-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 템플릿 created_at, updated_at 추가 및 수정

- src/main/resources/file-error-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/file-warn-appender.xml
- src/main/resources/logback-spring.xml
- [PS-87](https://packman-team.atlassian.net/browse/PS-87?atlOrigin=eyJpIjoiZWZjMWM2N2FmZWZmNGE3NTkzNDZjODlkMjQzZDAwOWEiLCJwIjoiaiJ9)
- 로그 TimeBasedRollingPolicy로 변경 및 경로 수정
- dev 환경 로그 설정
- 
[PS-87]: https://packman-team.atlassian.net/browse/PS-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 로그 설정 수정

- src/main/resources/file-error-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/file-warn-appender.xml
- src/main/resources/logback-spring.xml
- [PS-88](https://packman-team.atlassian.net/browse/PS-88?atlOrigin=eyJpIjoiNDQxZWQyNGRlMGQ0NGIxNjkzOTYxOTE3YmM5ZmQ3MzIiLCJwIjoiaiJ9)
- 로그 timezone을 Seoul로 설정
- 
[PS-88]: https://packman-team.atlassian.net/browse/PS-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 로그 timezone 설정

- src/main/resources/file-error-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/file-warn-appender.xml
> merge: branch 'develop' into main 

- src/main/java/packman/service/FolderService.java
- [PS-91](https://packman-team.atlassian.net/browse/PS-91)
-ZoneId.of("Asia/Seoul")로 timezone 설정
[PS-91]: https://packman-team.atlassian.net/browse/PS-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: localDate timezone 설정

- src/main/java/packman/service/AlarmService.java
- src/main/java/packman/service/HelpService.java
- src/main/java/packman/service/ListService.java
- src/main/java/packman/service/PackService.java
- src/main/java/packman/service/TemplateService.java
- src/main/java/packman/service/UserService.java
- src/main/java/packman/service/aloneList/AloneListCategoryService.java
- src/main/java/packman/service/aloneList/AloneListService.java
- src/main/java/packman/service/togetherList/TogetherListCategoryService.java
- src/main/java/packman/service/togetherList/TogetherListService.java
- src/main/java/packman/util/LogMessage.java
- [PS-92](https://packman-team.atlassian.net/browse/PS-92?atlOrigin=eyJpIjoiYjY4NzYyMDQ5NWU0NDViMWJkMzdiYjZjZjkxODEyODkiLCJwIjoiaiJ9)
- 로그 eventType 추가 및 패킹리스트 수정 api명 세분화
[PS-92]: https://packman-team.atlassian.net/browse/PS-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 로그 eventType 추가 및 패킹리스트 수정 api명 세분화
